export type LevixelNativeCallback = (json: string) => void

export type OpenLevixelNative = (
  optionsJson: string,
  callback: LevixelNativeCallback
) => void

export type CloseLevixelNative = (
  optionsJson: string,
  callback: LevixelNativeCallback
) => void

export type OnLevixelNativeEvent = (
  callback: LevixelNativeCallback
) => void

export type ResolveLevixelNativePaths = (
  pathsJson: string,
  callback: LevixelNativeCallback
) => void
